[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "google-generativeai>=0.3.0",
    "openai>=1.64.0",
    "speechrecognition>=3.14.1",
    "streamlit>=1.42.2",
]
